### ISSUE TITLE
Stopped working completely. Has any one else faced it ?

### ISSUE THREAD

**Issue by mhsina** [TobiasLaross/Hass-Lynk-Co#74]
Logger: aiohttp.server
Source: /usr/local/lib/python3.13/site-packages/aiohttp/web_protocol.py:481
First occurred: August 23, 2025 at 11:51:33 PM (1 occurrence)
Last logged: August 23, 2025 at 11:51:33 PM

Error handling request from …….
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/aiohttp/web_protocol.py", line 510, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/aiohttp/web_app.py", line 569, in _handle
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 92, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 83, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 26, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 86, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 242, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 41, in headers_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/http.py", line 73, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 83, in with_admin
    return await func(self, request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 227, in post
    return await super().post(request, flow_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 74, in wrapper
    return await method(view, request, data, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 121, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 336, in async_configure
    result = await self._async_configure(flow_id, user_input)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 383, in _async_configure
    result = await self._async_handle_step(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        flow, cur_step["step_id"], user_input
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 487, in _async_handle_step
    result: _FlowResultT = await getattr(flow, method)(user_input)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/lynkco/config_flow.py", line 91, in async_step_user
    ) = await login(email, password, session)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/lynkco/login_flow.py", line 43, in login
    page_view_id, referer_url = await getCombinedSigninAndSignup(
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<5 lines>...
    )
    ^
  File "/config/custom_components/lynkco/login_flow.py", line 178, in getCombinedSigninAndSignup
    async with session.get(url, params=params, headers=headers) as response:
               ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/aiohttp/client.py", line 1488, in __aenter__
    self._resp: _RetType = await self._coro
                           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/aiohttp/client.py", line 860, in _request
    raise NonHttpUrlRedirectClientError(r_url)
aiohttp.client_exceptions.NonHttpUrlRedirectClientError: msauth.com.lynkco.prod.lynkco-app://auth/?error=server_error&error_description=AADB2C90255%3a+The+claims+exchange+specified+in+technical+profile+%27LynkCo-LocalAccountSigninOnly-Mfa%27+did+not+complete+as+expected.+You+might+want+to+try+starting+your+session+over+from+the+beginning.%0d%0aCorrelation+ID%3a+9f360f45-7972-4352-8670-c9bf8ef0d671%0d%0aTimestamp%3a+2025-08-23+21%3a51%3a32Z%0d%0a

**Comment by heuerm18** [comment]
Had the same problem since 22.08.. After new login it is working for me again.

**Comment by mhsina** [comment]
removed it and added it again , but no success

**Comment by juanxu101** [comment]
Is it possible to start using it today? I just try to connect the new Link&Co 02 but it says: Unkown error

**Comment by Donkie** [comment]
Same issue for me, I dug a bit and it looks like Lynk&Co have added a captcha to the login flow, which is what is causing the login to fail.

**Comment by Dre74** [comment]
Same issue here: Removed "not updating" integration, on reinstall: stuck on login. (App is working fine)

**Comment by Donkie** [comment]
I have created a fork of this project where I have updated the login flow with a working solution. It is however not very user friendly. I will provide a more detailed guide on how to use it soon, but for now you can see if you can solve it yourself:

Add this repo as a custom repository in HACS and install: https://github.com/Donkie/Hass-Lynk-Co

Follow the instructions in the integration setup. Once you have finished logging in on Lynk & Co website, open your web browser developer console and copy paste the redirect URL that Lynk & Co tries to send you to but fails. It starts with "msauth://..." Paste that url into the integration setup field and it should work!

**Comment by mvanlijden** [comment]
> I have created a fork of this project where I have updated the login flow with a working solution. It is however not very user friendly. I will provide a more detailed guide on how to use it soon, but for now you can see if you can solve it yourself:
> 
> Add this repo as a custom repository in HACS and install: https://github.com/Donkie/Hass-Lynk-Co
> 
> Follow the instructions in the integration setup. Once you have finished logging in on Lynk & Co website, open your web browser developer console and copy paste the redirect URL that Lynk & Co tries to send you to but fails. It starts with "msauth://..." Paste that url into the integration setup field and it should work!

Cannot load your integration. Get an error on the config flow  {"message":"Invalid handler specified"}

**Comment by Langen38** [comment]
Same issue like mvanlijden.
Would be awesome if somebody could fix this so I can use my new car in HA

**Comment by mvanlijden** [comment]
> Same issue like mvanlijden. Would be awesome if somebody could fix this so I can use my new car in HA

Just download again with latest fix and now working with new login method!

**Comment by Langen38** [comment]
Nope... different browsers, different wifi/4g connections but the Donkie fork lets me login with name-pwd. I get a MFA SMS but after entering that al goes down a black hole....and the green okay button get an eternal rolling circkel
I dont get any new redirect URL that I can put in tje Hacs setup.

**Comment by mvanlijden** [comment]
> Nope... different browsers, different wifi/4g connections but the Donkie fork lets me login with name-pwd. I get a MFA SMS but after entering that al goes down a black hole....and the green okay button get an eternal rolling circkel I dont get any new redirect URL that I can put in tje Hacs setup.

Did you do this as stated by @Donkie ?

> Follow the instructions in the integration setup. Once you have finished logging in on Lynk & Co website, open your web browser developer console and copy paste the redirect URL that Lynk & Co tries to send you to but fails. It starts with "msauth://..." Paste that url into the integration setup field and it should work!

**Comment by Langen38** [comment]
Woeps... I should have better read the instructions 

Eurekaaaa 👍

**Comment by tommiefr** [comment]
I try to configure this but get this error after pasting the link in HA: no_vins_found

I receive the SMS but after that I see in the console the error (beside the msauth URL): because the scheme does not have a registered handler.

I have a 02, registered the app for 3 days. Can it be the car is not updated with the vin on Lynks side?
How to solve this?

**Comment by pjgrun** [comment]
Trying to install Donkie fork, but getting "Unknown error ocurred" after entering username and password.

Also, initial screen looks strange, showing blank prompts:

<img width="434" height="276" alt="Image" src="https://github.com/user-attachments/assets/aedc0a69-a07e-4b76-9e7e-ca1b7e94d0e5" />

Any help appreciated.

**Comment by Donkie** [comment]
My fork only adds the 2nd type of authentication.

Try clearing your browser cache for the display issue

**Comment by pjgrun** [comment]
Clearing cache did not work, but it worked switching to different browser. 
I was able to complete setup and integration is working again!
Surprised I can not set interval lower than 60 minutes. I was using 15 previously.
Thank you!

**Comment by pjgrun** [comment]
> Surprised I can not set interval lower than 60 minutes. I was using 15 previously.

Sorry, recalled that refresh every 15 minutes is handled via external automation, not via scan interval settings in integration configuration.

**Comment by ErikT80** [comment]
Great work @Donkie! Let's see if we can keep this integration working in the future :-). As @TobiasLaross  mentions he is not maintaining the repo anymore, should we consider your fork the one to keep investing in? 😊

**Comment by Donkie** [comment]
Thanks! I still want to document this a bit better before making it official. Maybe someone can help with taking a screen capture or something, especially showing where to find the redirect url?

**Comment by madtraxx18** [comment]
If I use your version, will all the entities remain the same? Have you also seen the other post regarding the deprecation of some code which the current version uses?

**Comment by Donkie** [comment]
Entities remain the same.

No I havent seen that

**Comment by Ferrox85** [comment]
Grabbing the redirect link is a bit hard. Advice, use an incognito browser and open the console. There you see the redirect url failed to load. Use that one to add to this intergration set-up. Many thanks for the great work @Donkie!

**Comment by b12e** [comment]
Edit: https://github.com/b12e/hacs_lynkco_2025 😊 Ignore the below.
---
Has anyone tried with the 2025 facelift of the 01?

I keep on getting 'no vin found'. I tried to log the requests an am getting this:
```
2025-11-22 18:08:00.628 ERROR (MainThread) [custom_components.lynkco.config_flow] [VIN DISCOVERY] Extracted user_id: REDACTED
2025-11-22 18:08:00.628 ERROR (MainThread) [custom_components.lynkco.config_flow] [VIN DISCOVERY] CCC token exists: True, length: 1136
2025-11-22 18:08:00.628 ERROR (MainThread) [custom_components.lynkco.login_flow] [VIN API] Requesting VINs from: https://user-lifecycle-tls.aion.connectedcar.cloud/user-lifecycle/api/provisioning/v1/users/REDACTED/activevehicles
2025-11-22 18:08:00.628 ERROR (MainThread) [custom_components.lynkco.login_flow] [VIN API] User ID: REDACTED
2025-11-22 18:08:00.628 ERROR (MainThread) [custom_components.lynkco.login_flow] [VIN API] CCC token length: 1136
2025-11-22 18:08:00.924 ERROR (MainThread) [custom_components.lynkco.login_flow] [VIN API] Response status: 200
2025-11-22 18:08:00.924 ERROR (MainThread) [custom_components.lynkco.login_flow] [VIN API] Response body: {"roles":[]}
2025-11-22 18:08:00.924 ERROR (MainThread) [custom_components.lynkco.login_flow] [VIN API] Parsed JSON response: {'roles': []}
2025-11-22 18:08:00.924 ERROR (MainThread) [custom_components.lynkco.login_flow] [VIN API] Roles array: []
2025-11-22 18:08:00.924 ERROR (MainThread) [custom_components.lynkco.login_flow] [VIN API] Extracted VINs: []
2025-11-22 18:08:00.924 ERROR (MainThread) [custom_components.lynkco.config_flow] [VIN DISCOVERY] Retrieved VINs from API: []
2025-11-22 18:08:00.924 ERROR (MainThread) [custom_components.lynkco.config_flow] [VIN DISCOVERY] No VINs found for the user - check the API response logs above

```
I modified the plugin to allow manual entry of a VIN when none are found, and then I get through the setup, but get a 403 on getting the vehicle data:
`Failed to fetch vehicle data, HTTP status: 403, response: {"timestamp":"2025-11-22T17:17:02.099+00:00","status":403,"error":"Forbidden","path":"/api/v1/vds/vehicles/VIN-REMOVED/data/record"}`

The mobile app works just fine, and I can see the VIN on the website.

Edit: it seems there's a different set of APIs for the facelift 01. I tried to intercept network traffic between my phone and the internet, and got up to `https://lynkco-apis.ecloudeu.com` as hostname.

**Comment by pjgrun** [comment]
> Entities remain the same.
> 
> No I havent seen that

See: https://github.com/TobiasLaross/Hass-Lynk-Co/issues/78#issue-3609487055

**Comment by whizzi** [comment]
> Thanks! I still want to document this a bit better before making it official. Maybe someone can help with taking a screen capture or something, especially showing where to find the redirect url?

If I'm able to get it working, I am more than happy to describe it. For now, I'm stuck at receiving an http 400 error.
`2025-11-24 08:16:44.606 ERROR (MainThread) [custom_components.lynkco.login_flow] Failed to obtain tokens. Status code: 400
2025-11-24 08:16:44.606 ERROR (MainThread) [custom_components.lynkco.login_flow] Failed to get tokens. Exiting`

So this is after the following steps:

1. Add the Lynk&Co integration and click on Redirect login
2. Open the URL that appears in an incognito browser
3. Enter username + password on this new page and log in
4. Press F12  in the browser (Firefox) and wait until the SMS arrives
5. Enter the SMS code into the Lynk&Co browser
6. Watch the console:
In the console there's a GET https://login.lynkco.com/...signin_mfa/api/$tokenstuff

This returns a 302, but in the header there is a
location: msauth://prod.lynkco.app.crisp.prod/2jm$tokenjunk

I copy this specific header into the field on the HA page, and that immediately gives a 400 error.

**Comment by timomito** [comment]
invalid_redirect_uri 
i can't find de url didn't see "msauth"in the developer tool in the browser. What am i doing wrong?

**Comment by bjornkoster89** [comment]
> invalid_redirect_uri i can't find de url didn't see "msauth"in the developer tool in the browser. What am i doing wrong?

I can’t find the URI either.

I hope Donky can share screenshots so we can test it.

In the console I get a warning:

hCaptcha render/execute failed: 
Object { cause: "missing-captcha", message: "No hCaptcha exists." }

**Comment by whizzi** [comment]
<img width="1043" height="1020" alt="Image" src="https://github.com/user-attachments/assets/9108563b-cf26-485f-baee-eeb2503ef327" />

Not sure if this helps, but **after** the username + password on Lynk&Co's page, you will go to a new page where you can fill in a code that you receive through SMS. 

Filling in that code will launch the redirect (and fails) and that's when the msauth:// link occurs inside the GET message (which errors with a 302 and a unknown protocol), as seen on the screenshot (Firefox under KDE)

However, this code (starting with msauth://) will return an error 400 in HomeAssistant and it won't let me log in. 

This is the only time I have found a msauth:// link in the whole login sequence.

**Comment by tommiefr** [comment]
> I try to configure this but get this error after pasting the link in HA: no_vins_found
> 
> I receive the SMS but after that I see in the console the error (beside the msauth URL): because the scheme does not have a registered handler.
> 
> I have a 02, registered the app for 3 days. Can it be the car is not updated with the vin on Lynks side? How to solve this?

Any update or is this integration not suitable for C02? Only for C01?

**Comment by Donkie** [comment]
I have a 01, have no way of testing or verifying this for a 02. Do they even use the same app?

**Comment by tommiefr** [comment]
> I have a 01, have no way of testing or verifying this for a 02. Do they even use the same app?

I do think they use the same app. Can be the software is different....

**Comment by ErikT80** [comment]
@Donkie Is it just me or it seems like the data is not updated anymore within the integration. Some entities are unavailable and others have the same value as days before although they have changed (for instance battery %). Or is there an issue on Lynk' side?

**Comment by pjgrun** [comment]
> [@Donkie](https://github.com/Donkie) Is it just me or it seems like the data is not updated anymore within the integration. Some entities are unavailable and others have the same value as days before although they have changed (for instance battery %). Or is there an issue on Lynk' side?

Still OK here.

**Comment by ErikT80** [comment]
> > [@Donkie](https://github.com/Donkie) Is it just me or it seems like the data is not updated anymore within the integration. Some entities are unavailable and others have the same value as days before although they have changed (for instance battery %). Or is there an issue on Lynk' side?
> 
> Still OK here.

Hmm weird, I get these errors in my log:

Data path not found: ['vehicle_shadow', 'vrs', 'seatBeltStatus', 'driverRear', 'fastened'], coordinator.data: {'vehicle_record': {'vin': 'XXXXXX', 'position': {'latitude': XXXX, 'longitude': XXXX, 'altitude': 7, 'canBeTrusted': True, 'vehicleUpdatedAt': '2025-11-21T14:50:23Z'}, 'odometer': {'odometerKm': 37624, 'odometerMile': 23378, 'vehicleUpdatedAt': '2025-11-21T14:50:23Z'}, 'speed': {'speed': 0, 'direction': 0, 'speedUnit': '0', 'vehicleUpdatedAt': '2025-11-21T14:50:23Z'}, 'fuel': {'level': 15.2, 'fuelType': 'PETROL_PLUGIN_HYBRID', 'distanceToEmpty': 170, 'levelStatus': 3, 'averageConsumption': 3.7037036, 'averageConsumptionLatestDrivingCycle': 6.6, 'averageConsumptionUnit': 'L_PER_HECTO_KILO_M', 'vehicleUpdatedAt': '2025-11-21T14:50:23Z'}, 'battery': {'chargeLevel': 0, 'charge': 'CHARGE_UNSPECIFIED', 'health': 0, 'powerLevel': 0, 'energyLevel': 0, 'voltage': 147, 'vehicleUpdatedAt': '2025-11-21T14:47:25Z'}, 'climate': {'interiorTemp': {'temp': 9.900002, 'Quality': 'ACCURATE_DATA', 'Unit': 'CELSIUS'}, 'exteriorTemp': {'temp': 6.0, 'Quality': 'ACCURATE_DATA', 'Unit': 'CELSIUS'}, 'preClimateActive': False, 'vehicleUpdatedAt': '2025-11-21T14:47:25Z'}, 'electricStatus': {'chargeLevel': 100.0, 'timeToFullyCharged': 10, 'distanceToEmptyOnBatteryOnly': 67, 'vehicleUpdatedAt': '2025-11-22T10:00:12Z'}, 'maintenanceStatus': {'distanceToService': 16746, 'daysToService': 276, 'engineHoursToService': 415, 'engineCoolantTemperature': 40, 'serviceWarningStatus': 'SERVICE_WARNING_STATUS_NORMAL', 'engineOilLevelStatus': 'ENGINE_OIL_LEVEL_STATUS_NORMAL', 'engineOilPressureStatus': 'ENGINE_OIL_PRESSURE_STATUS_NORMAL', 'washerFluidLevelStatus': 'WASHER_FLUID_LEVEL_STATUS_NORMAL', 'vehicleUpdatedAt': '2025-11-21T14:47:25Z'}, 'trip': {'avgSpeed': 55, 'avgSpeedLastDrivingCycle': 17, 'tripMeter': 3223.6, 'tripMeter2': 13.1, 'vehicleUpdatedAt': '2025-11-21T14:50:23Z'}, 'updatedAt': '2025-11-22T10:00:13.888Z', 'createdAt': '2022-09-22T14:58:44.979Z'}, 'vehicle_shadow': {'bvs': {}, 'evs': {}, 'vcs': {'preclimateActive': False}, 'vls': {}, 'vms': {}, 'vrs': {}}, 'vehicle_address': 'XXXX', 'vehicle_address_raw': '32, XXXXX'}

Did Lynk&Co change the api response maybe?

**Comment by Donkie** [comment]
Hmm that aspect should not be affected by my updates. For me it has always been flaky, with no difference before or after my changes

**Comment by home89c3** [comment]
<img width="1646" height="301" alt="Image" src="https://github.com/user-attachments/assets/271c7168-ed35-46de-92ca-255a7acb3d95" />
Same here when i reload some of them have value but not all also the command dosent work anymore from this morning . also on the application not updated any data ?
if i try to add againe integration give unexpected error :( Hope this will be solved soon.

**Comment by home89c3** [comment]
<img width="403" height="189" alt="Image" src="https://github.com/user-attachments/assets/521d4076-af79-422d-80e9-cd500752b3ab" />

I delete old one restart and try to instal againe 
but give me error 
Logger: homeassistant
Source: runner.py:238
First occurred: 16:14:22 (3 occurrences)
Last logged: 16:14:37

Error doing job: Unclosed client session (None)
Error doing job: Unclosed connector (None)

**Comment by ErikT80** [comment]
> <img alt="Image" width="1646" height="301" src="https://private-user-images.githubusercontent.com/111180553/519764197-271c7168-ed35-46de-92ca-255a7acb3d95.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjQyNTc0NjgsIm5iZiI6MTc2NDI1NzE2OCwicGF0aCI6Ii8xMTExODA1NTMvNTE5NzY0MTk3LTI3MWM3MTY4LWVkMzUtNDZkZS05MmNhLTI1NWE3YWNiM2Q5NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUxMTI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MTEyN1QxNTI2MDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zZjhkMDRjYTBlNTYyMjQzNGY1MzE4ZTc3OWZkOWVjZWFlZTg4NTU4NDFjNDIyZGNlOGZhYjgyOGNlYWIxODQ5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.TUc3KZqo3iTNO9q7k7unCuaG0z8luNQUJRx9PQG-sb0"> Same here when i reload some of them have value but not all also the command dosent work anymore from this morning . also on the application not updated any data ? if i try to add againe integration give unexpected error :( Hope this will be solved soon.

I just noticed that my car also doesn't have an internet connection anymore.. So seems difficult for the Lynk to send data.. probably an issue on lynk side. I will wait for a while and see if it improves.

**Comment by jannegpriv** [comment]
Anyone that knows more on the correct endpoints for Lynk&Co models 02 and 08?
I've recently upgraded to the 08 model and I get a 403 when fetching vehicle data.

**Comment by home89c3** [comment]
Any news about how to solve this please!

**Comment by bjornkoster89** [comment]
> I have created a fork of this project where I have updated the login flow with a working solution. It is however not very user friendly. I will provide a more detailed guide on how to use it soon, but for now you can see if you can solve it yourself:
> 
> Add this repo as a custom repository in HACS and install: https://github.com/Donkie/Hass-Lynk-Co
> 
> Follow the instructions in the integration setup. Once you have finished logging in on Lynk & Co website, open your web browser developer console and copy paste the redirect URL that Lynk & Co tries to send you to but fails. It starts with "msauth://..." Paste that url into the integration setup field and it should work!

Can you make a manuel with pictures of this installation? I have url error.

**Comment by home89c3** [comment]
They are other persona how succesfuly use this integration ?
I try Donkie integration but dosent let me to login , say unexpected error ...
I use in the past Tobias integration and now i try to refresh token but without any success 
I try also to modify 
login_b2c_url = "https://login.lynkco.com/lynkcoprod.onmicrosoft.com/b2c_1a_signin_mfa/"
with "https://login.lynkco.com/lynkcoprod.onmicrosoft.com/B2C_1A_SIGNIN_ONLY/" from spy the web browser i see this is used 

ALso i try to find msauth but i dont see any respnse like this .
I manage to get some information like ccc_token and user_id but i dont know how to get refresh_token. i can try to put manual this on HA on this location homeassistant->.storage->lynkco_tokens 



<img width="1492" height="279" alt="Image" src="https://github.com/user-attachments/assets/72a70119-169e-4ded-bce8-9eb0a2cdc995" />

**Comment by whizzi** [comment]
> > I have created a fork of this project where I have updated the login flow with a working solution. It is however not very user friendly. I will provide a more detailed guide on how to use it soon, but for now you can see if you can solve it yourself:
> > Add this repo as a custom repository in HACS and install: https://github.com/Donkie/Hass-Lynk-Co
> > Follow the instructions in the integration setup. Once you have finished logging in on Lynk & Co website, open your web browser developer console and copy paste the redirect URL that Lynk & Co tries to send you to but fails. It starts with "msauth://..." Paste that url into the integration setup field and it should work!
> 
> Can you make a manuel with pictures of this installation? I have url error.

I have put screenshots [here](https://github.com/TobiasLaross/Hass-Lynk-Co/issues/74#issuecomment-3577365690)

**Comment by home89c3** [comment]
> > > I have created a fork of this project where I have updated the login flow with a working solution. It is however not very user friendly. I will provide a more detailed guide on how to use it soon, but for now you can see if you can solve it yourself:
> > > Add this repo as a custom repository in HACS and install: https://github.com/Donkie/Hass-Lynk-Co
> > > Follow the instructions in the integration setup. Once you have finished logging in on Lynk & Co website, open your web browser developer console and copy paste the redirect URL that Lynk & Co tries to send you to but fails. It starts with "msauth://..." Paste that url into the integration setup field and it should work!
> > 
> > 
> > Can you make a manuel with pictures of this installation? I have url error.
> 
> I have put screenshots [here](https://github.com/TobiasLaross/Hass-Lynk-Co/issues/74#issuecomment-3577365690)

I try to cache same here but i dont find the link i try also to use some tools like reqable to spy the app communication and now they block me 😅. 
I don't understand how you find the msauth link...  How you spy f12 on chrome on android? On laptop is not same b2c_1a_signn_mfa like on android app 🤔. Please help me to understand 

<img width="1080" height="565" alt="Image" src="https://github.com/user-attachments/assets/dc1b736e-bcb0-4a51-8622-c5c9f3eb6661" />

**Comment by whizzi** [comment]
> > > > I have created a fork of this project where I have updated the login flow with a working solution. It is however not very user friendly. I will provide a more detailed guide on how to use it soon, but for now you can see if you can solve it yourself:
> > > > Add this repo as a custom repository in HACS and install: https://github.com/Donkie/Hass-Lynk-Co
> > > > Follow the instructions in the integration setup. Once you have finished logging in on Lynk & Co website, open your web browser developer console and copy paste the redirect URL that Lynk & Co tries to send you to but fails. It starts with "msauth://..." Paste that url into the integration setup field and it should work!
> > > 
> > > 
> > > Can you make a manuel with pictures of this installation? I have url error.
> > 
> > 
> > I have put screenshots [here](https://github.com/TobiasLaross/Hass-Lynk-Co/issues/74#issuecomment-3577365690)
> 
> I try to cache same here but i dont find the link i try also to use some tools like reqable to spy the app communication and now they block me 😅. I don't understand how you find the msauth link... How you spy f12 on chrome on android? On laptop is not same b2c_1a_signn_mfa like on android app 🤔. Please help me to understand

I'm using a normal computer with Firefox. No clue how this could be done on Android. I only see the msauth code **after** I have responded with a code that I have received on SMS. 

But it doesn't work for me either, even when I put in the msauth link, it will respond with error 400. So, it seems something has changed on Lynk&Co side that broke the entire login (from either the original TobiasLaross version as well as the @Donkie version)

**Comment by home89c3** [comment]
> > > > > I have created a fork of this project where I have updated the login flow with a working solution. It is however not very user friendly. I will provide a more detailed guide on how to use it soon, but for now you can see if you can solve it yourself:
> > > > > Add this repo as a custom repository in HACS and install: https://github.com/Donkie/Hass-Lynk-Co
> > > > > Follow the instructions in the integration setup. Once you have finished logging in on Lynk & Co website, open your web browser developer console and copy paste the redirect URL that Lynk & Co tries to send you to but fails. It starts with "msauth://..." Paste that url into the integration setup field and it should work!
> > > > 
> > > > 
> > > > Can you make a manuel with pictures of this installation? I have url error.
> > > 
> > > 
> > > I have put screenshots [here](https://github.com/TobiasLaross/Hass-Lynk-Co/issues/74#issuecomment-3577365690)
> > 
> > 
> > I try to cache same here but i dont find the link i try also to use some tools like reqable to spy the app communication and now they block me 😅. I don't understand how you find the msauth link... How you spy f12 on chrome on android? On laptop is not same b2c_1a_signn_mfa like on android app 🤔. Please help me to understand
> 
> I'm using a normal computer with Firefox. No clue how this could be done on Android. I only see the msauth code **after** I have responded with a code that I have received on SMS.
> 
> But it doesn't work for me either, even when I put in the msauth link, it will respond with error 400. So, it seems something has changed on Lynk&Co side that broke the entire login (from either the original TobiasLaross version as well as the [@Donkie](https://github.com/Donkie) version)

I try againe Tobias integration work to login but doesnt send any sms to finish the login and i have 3 errors...
I try also to login in paralel on app to use same code they say is valid for 20 minute but dosent work probably they are diffrent token :( .
I will try to debug the app and ssee maybe i could adjusted , i am not a software  engineer on Python :(  we need Tobias or DOnkie to solve also i think  we will need to buy some coffee to them :)


This error originated from a custom integration.

Logger: custom_components.lynkco.login_flow
Source: custom_components/lynkco/login_flow.py:364
integration: Lynk & Co (documentation, issues)
First occurred: 11:37:08 (1 occurrence)
Last logged: 11:37:08

GET redirect request failed or did not contain redirect. status: 200
is this line  redirect_uri = "msauth.com.lynkco.prod.lynkco-app://auth" so i know the lynko change this to another link
This error originated from a custom integration.
//////////////////////////////////////////////////////////////////////////////////
Logger: custom_components.lynkco.login_flow
Source: custom_components/lynkco/login_flow.py:103
integration: Lynk & Co (documentation, issues)
First occurred: 11:37:08 (1 occurrence)
Last logged: 11:37:08
And here is client id client_id = "813902c0-0579-43f3-a767-6601c2f5fdbe" is change also this ....
Failed to get redirect code. Exiting...


<img width="1628" height="230" alt="Image" src="https://github.com/user-attachments/assets/369f6ab3-2614-4f9c-bfa7-7205211a9557" />

<img width="510" height="352" alt="Image" src="https://github.com/user-attachments/assets/163f0d95-cebe-4a64-a06e-4ebffe018eaa" />

**Comment by bjornkoster89** [comment]
Good day, I was wondering how things are progressing with the integration of the fork by Tobias Laros.

Do you have any idea when the updated integration will be working? At the moment, it’s still not possible to obtain a new token.

And even if a new token can be obtained, I (and several others) still haven’t been able to get the car to connect.

I hope we’ll get some more information on this soon.

Many thanks for continuing the work on this, “Donkey” 💪

**Comment by home89c3** [comment]
Finally i manage to use 1.10.0 Donkey integration. So
Step 1 : detele or rename old integration you have 1 directory in component and also token from old inintegration. 

![Image](https://github.com/user-attachments/assets/f81ff58f-e303-4bf0-b8a5-78ddd3b14879)

Step2 add in hacs the new integraion 1.10.0 Donkey download

Step 3 restart the HA

Step 4 add integration in device and select redirect link 

![Image](https://github.com/user-attachments/assets/6efbd7e7-9ca2-4f3f-b293-7e8525525df1)
Step 5 press on blue link afthwr that prw F12 or Fn+F12 depend of the browser.
Step 6 go to console and afther that put user + password log in
Step 7 put the sms cod number
Step 8 and when you put the nunber you will se an error message on console failed to launched. 

![Image](https://github.com/user-attachments/assets/944448de-0779-4448-8e7d-e06e15cc3d97)

Step9 copy from msauth:..... Until end and past to home assitant redirect URL.
Step 10 finished now should work.
Thx @Donkie.
Hope is working this they are my steps. 
@whizzi  i think you let the old token file on ha. 
@bjornkoster89 here step by step

**Comment by whizzi** [comment]
Removed integration and I did find an old token, which I removed. Re-added the Donkie integration and followed the steps. But, same result:
`2025-12-03 17:40:31.022 ERROR (MainThread) [custom_components.lynkco.login_flow] Failed to obtain tokens. Status code: 400`

With the msauth:// link copied and pasted into the HA. 

The error 400 is coming from the remote server. I am running Linux (KDE) with Firefox, but I don't think this is the cause. My HA is running on a Docker on my QNAP NAS.

**Comment by home89c3** [comment]
> Removed integration and I did find an old token, which I removed. Re-added the Donkie integration and followed the steps. But, same result: `2025-12-03 17:40:31.022 ERROR (MainThread) [custom_components.lynkco.login_flow] Failed to obtain tokens. Status code: 400`
> 
> With the msauth:// link copied and pasted into the HA.
> 
> The error 400 is coming from the remote server. I am running Linux (KDE) with Firefox, but I don't think this is the cause. My HA is running on a Docker on my QNAP NAS.

I add new line here  to plot on log exactly the data, header and url . 

<img width="1080" height="2400" alt="Image" src="https://github.com/user-attachments/assets/2d1e9bff-5370-42b6-9d34-24dba664e4d8" />

**Comment by bjornkoster89** [comment]
> Finally i manage to use 1.10.0 Donkey integration. So Step 1 : detele or rename old integration you have 1 directory in component and also token from old inintegration.
> 
> ![Image](https://github.com/user-attachments/assets/f81ff58f-e303-4bf0-b8a5-78ddd3b14879)
> 
> Step2 add in hacs the new integraion 1.10.0 Donkey download
> 
> Step 3 restart the HA
> 
> Step 4 add integration in device and select redirect link
> 
> ![Image](https://github.com/user-attachments/assets/6efbd7e7-9ca2-4f3f-b293-7e8525525df1) Step 5 press on blue link afthwr that prw F12 or Fn+F12 depend of the browser. Step 6 go to console and afther that put user + password log in Step 7 put the sms cod number Step 8 and when you put the nunber you will se an error message on console failed to launched.
> 
> ![Image](https://github.com/user-attachments/assets/944448de-0779-4448-8e7d-e06e15cc3d97)
> 
> Step9 copy from msauth:..... Until end and past to home assitant redirect URL. Step 10 finished now should work. Thx [@Donkie](https://github.com/Donkie). Hope is working this they are my steps. [@whizzi](https://github.com/whizzi) i think you let the old token file on ha. [@bjornkoster89](https://github.com/bjornkoster89) here step by step

Holy shit, it works. I didn’t delete the old token (the token was invalid). I did remove the old Lynk & Co integration from HACS, restarted HA, and then added Donkie’s fork (https://github.com/Donkie/Hass-Lynk-Co
) to HACS and downloaded it. After that I restarted HA again.
Then I added a new device under Devices and searched for Lynk & Co. Add that, select the bottom option, click the URL link, enter your Lynk & Co account login details, and you’ll receive an SMS — enter that code.
Then go to ‘Developer Tools’ (in Google Chrome), open the console, and you’ll see the link there. Right-click the entire link, copy it, and paste it into HA where you need to enter the code.

I don’t know what I was doing wrong before, but now it worked on the first try.

![Image](https://github.com/user-attachments/assets/e87750a3-683b-46c5-8f13-bd1bfb328781)

**Comment by bjornkoster89** [comment]
Also the Engine will remote start for Climate.

![Image](https://github.com/user-attachments/assets/a0327943-80ae-401e-929f-6f0236010d89)
<img width="645" height="1398" alt="Image" src="https://github.com/user-attachments/assets/2b823e8f-9eed-4a27-a0df-f4568c22070b" />

**Comment by home89c3** [comment]
> Also the Engine will remote start for Climate.
> 
> ![Image](https://github.com/user-attachments/assets/a0327943-80ae-401e-929f-6f0236010d89) <img alt="Image" width="645" height="1398" src="https://private-user-images.githubusercontent.com/42722776/522064763-2b823e8f-9eed-4a27-a0df-f4568c22070b.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjQ3OTE2NDEsIm5iZiI6MTc2NDc5MTM0MSwicGF0aCI6Ii80MjcyMjc3Ni81MjIwNjQ3NjMtMmI4MjNlOGYtOWVlZC00YTI3LWEwZGYtZjQ1NjhjMjIwNzBiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTEyMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUxMjAzVDE5NDkwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMzMmRiOTNiN2U3MDUwODU1MjVlN2MyZGY1M2M4NWU0NzBlMmRkZjY0MjNkYzVlZGQ5NTAyNjk1YWM3ZjE3YjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.0CGJ1vcHF_tQX6T-08dFsc6aVG5YQtg_Yu4maFuml_k">

In the past work for 3 minutes and afther that stop if dosent have plug on charging... Is runing more then 3 minutea? Is start also the petrol engine?

**Comment by bjornkoster89** [comment]
> > Also the Engine will remote start for Climate.
> > ![Image](https://github.com/user-attachments/assets/a0327943-80ae-401e-929f-6f0236010d89) <img alt="Image" width="645" height="1398" src="https://private-user-images.githubusercontent.com/42722776/522064763-2b823e8f-9eed-4a27-a0df-f4568c22070b.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjQ3OTE2NDEsIm5iZiI6MTc2NDc5MTM0MSwicGF0aCI6Ii80MjcyMjc3Ni81MjIwNjQ3NjMtMmI4MjNlOGYtOWVlZC00YTI3LWEwZGYtZjQ1NjhjMjIwNzBiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTEyMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUxMjAzVDE5NDkwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMzMmRiOTNiN2U3MDUwODU1MjVlN2MyZGY1M2M4NWU0NzBlMmRkZjY0MjNkYzVlZGQ5NTAyNjk1YWM3ZjE3YjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.0CGJ1vcHF_tQX6T-08dFsc6aVG5YQtg_Yu4maFuml_k">
> 
> In the past work for 3 minutes and afther that stop if dosent have plug on charging... Is runing more then 3 minutea? Is start also the petrol engine?


When the Battery is emty, the car will start with petrol.
I start my car on my work, i dont know or the engine is still on now🤣🙈. 

With  20 hours iam back on my work, and i will check it.

**Comment by home89c3** [comment]
> > > Also the Engine will remote start for Climate.
> > > ![Image](https://github.com/user-attachments/assets/a0327943-80ae-401e-929f-6f0236010d89) <img alt="Image" width="645" height="1398" src="https://private-user-images.githubusercontent.com/42722776/522064763-2b823e8f-9eed-4a27-a0df-f4568c22070b.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjQ3OTE2NDEsIm5iZiI6MTc2NDc5MTM0MSwicGF0aCI6Ii80MjcyMjc3Ni81MjIwNjQ3NjMtMmI4MjNlOGYtOWVlZC00YTI3LWEwZGYtZjQ1NjhjMjIwNzBiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTEyMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUxMjAzVDE5NDkwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMzMmRiOTNiN2U3MDUwODU1MjVlN2MyZGY1M2M4NWU0NzBlMmRkZjY0MjNkYzVlZGQ5NTAyNjk1YWM3ZjE3YjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.0CGJ1vcHF_tQX6T-08dFsc6aVG5YQtg_Yu4maFuml_k">
> > 
> > 
> > In the past work for 3 minutes and afther that stop if dosent have plug on charging... Is runing more then 3 minutea? Is start also the petrol engine?
> 
> When the Battery is emty, the car will start with petrol. I start my car on my work, i dont know or the engine is still on now🤣🙈.
> 
> With 20 hours iam back on my work, and i will check it.
You can stop from action.
Is strange now doesn't work any comand (work fine 2 h ago :( flashing and honking, battery update)  i dont have any error log in HA 🤔.
Also the app let you to log in same time when you are in HA? 

<img width="1080" height="2400" alt="Image" src="https://github.com/user-attachments/assets/a4aa7224-aee3-4faf-b17c-332c3d536b4c" />

**Comment by bjornkoster89** [comment]
![Image](https://github.com/user-attachments/assets/1deed687-3f3e-4b91-929c-9b9d5dfbaf4f)
![Image](https://github.com/user-attachments/assets/f48c11c8-e12b-425b-a1fd-914e40d92c75)
<img width="645" height="1398" alt="Image" src="https://github.com/user-attachments/assets/08ad2fd4-9dcc-4a21-8035-b45421b282e6" />
<img width="645" height="1398" alt="Image" src="https://github.com/user-attachments/assets/09b39bd5-3a1a-4c7f-b8d7-ad3e16ebafde" />

**Comment by whizzi** [comment]
> > Removed integration and I did find an old token, which I removed. Re-added the Donkie integration and followed the steps. But, same result: `2025-12-03 17:40:31.022 ERROR (MainThread) [custom_components.lynkco.login_flow] Failed to obtain tokens. Status code: 400`
> > With the msauth:// link copied and pasted into the HA.
> > The error 400 is coming from the remote server. I am running Linux (KDE) with Firefox, but I don't think this is the cause. My HA is running on a Docker on my QNAP NAS.
> 
> I add new line here to plot on log exactly the data, header and url .

Ok, that's new.

So, I installed Chromium browser and did the entire reintegration, and now it works!

Comparing the 2 msauth lines. Firefox has 1025 characters (entire line) and Chromium has 1511 characters. 

Basically, if you want to use this integration, **don't** use Firefox's debug mode :/

**Comment by home89c3** [comment]
> > > Removed integration and I did find an old token, which I removed. Re-added the Donkie integration and followed the steps. But, same result: `2025-12-03 17:40:31.022 ERROR (MainThread) [custom_components.lynkco.login_flow] Failed to obtain tokens. Status code: 400`
> > > With the msauth:// link copied and pasted into the HA.
> > > The error 400 is coming from the remote server. I am running Linux (KDE) with Firefox, but I don't think this is the cause. My HA is running on a Docker on my QNAP NAS.
> > 
> > 
> > I add new line here to plot on log exactly the data, header and url .
> 
> Ok, that's new.
> 
> So, I installed Chromium browser and did the entire reintegration, and now it works!
> 
> Comparing the 2 msauth lines. Firefox has 1025 characters (entire line) and Chromium has 1511 characters.
> 
> Basically, if you want to use this integration, **don't** use Firefox's debug mode :/

Good to know.
My again don't work from this morning  i dont have any error but don't refresh the value any more and don't work any command. Yesterday work fine. Mybe is a problem fron lynk&co server 🤔.
Your work fine all the future? 
Also i find this message so with ha 2025.12 will not work some entity. Now i have ha 2025.11. 
Logger: homeassistant.helpers.frame
Source: helpers/frame.py:350
First occurred: 10:39:51 (1 occurrence)
Last logged: 10:39:51

Detected that custom integration 'lynkco' sets option flow config_entry explicitly, which is deprecated at custom_components/lynkco/config_flow.py, line 276: self.config_entry = config_entry. This will stop working in Home Assistant 2025.12, please create a bug report at https://github.com/tobiaslaross/Hass-Lynk-Co/issues

**Comment by zygios** [comment]
Integration for me still not working, tryed Donkie’s fork with email and password not working, with direct link with link msauth://prod.lynkco.app.crisp.prod/xxxxx and getting error **no_vins_found**. Before instaling Donkie's fork I deleted old token.

Downloading Donkie's c3061cff6dc871e01e62fd240bccbc40bc1d9d2e commit getting error in log:
[<Integration Donkie/Hass-Lynk-Co>] Failed to download zipball
Traceback (most recent call last):
  File "/config/custom_components/hacs/repositories/base.py", line 631, in download_content
    await self.download_repository_zip()
  File "/config/custom_components/hacs/repositories/base.py", line 677, in download_repository_zip
    raise HacsException(f"[{self}] Failed to download zipball")
custom_components.hacs.exceptions.HacsException: [<Integration Donkie/Hass-Lynk-Co>] Failed to download zipball

**Comment by madtraxx18** [comment]
Please note!!

Do not install version 2025.12.xx it will not allow to configure the experimental features! Most likely due to this:

Detected that custom integration 'lynkco' sets option flow config_entry explicitly, which is deprecated at custom_components/lynkco/config_flow.py, line 276: self.config_entry = config_entry. This will stop working in Home Assistant 2025.12, please create a bug report at https://github.com/tobiaslaross/Hass-Lynk-Co/issues

Trying to configure the settings in version 2025.12.xx wil give you an error 500 popup when you try to configure the integration (enabling experimental features).

@Donkie do you think that you can resolve this issue?

**Comment by madtraxx18** [comment]
@Donkie 'fixed it by:

In the addon config file:

search for the line mentioned in the warning:

self.config_entry = config_entry

Should be replaced by:

self._config_entry = config_entry

Now you can safely update to HA 2025.12.xx

**Comment by home89c3** [comment]
> [@Donkie](https://github.com/Donkie) 'fixed it by:
> 
> In the addon config file:
> 
> search for the line mentioned in the warning:
> 
> self.config_entry = config_entry
> 
> replace it with: self.config_entry = config_entry
> 
> Now you can safely update to HA 2025.12.xx

I dont understand replace it same line of code ? i dont see any chnage .

**Comment by madtraxx18** [comment]
Sorry mate:

self.config_entry = config_entry

Should be replaced by:

self._config_entry = config_entry

I'll edit my prevrious post to prevent confusion

**Comment by Donkie** [comment]
I've pushed an update now that fixes the config_entry issue.

**Comment by W-Slotboom** [comment]
@Donkie , you are a hero!

**Comment by home89c3** [comment]
Anyone have issues with the commanda? All the sensors and status works fine only the actions are not. It is 2 days and still doesn't work, i try reload the integration and same.... If i get the respons say ack true so the server recive the command? 

<img width="1080" height="1257" alt="Image" src="https://github.com/user-attachments/assets/fed115ee-e75a-49d0-9d09-a0d9369d0ddd" />

**Comment by madtraxx18** [comment]
Same here, haven’t tested the Lynk co app itself yet

**Comment by madtraxx18** [comment]
It is also not working with the app itself.

**Comment by Donkie** [comment]
Got the same issue. Hopefully it resolves soon. If it's broken in the app as well maybe they just have some backend problems. I doubt anyone is working actively on these systems anymore for the 01.
